"""init_tables

Revision ID: 7081af3ca26c
Revises: 9de8f38953d7
Create Date: 2021-03-12 14:28:00.416266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7081af3ca26c'
down_revision = '9de8f38953d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type')
    # ### end Alembic commands ###
